apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: jyotiraul74@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-private-key
    solvers:
    - dns01:
        route53:
          region: ap-south-1  # Change to your AWS region
          hostedZoneID: ""   # Optional; cert-manager will auto-detect if left blank
          accessKeyIDSecretRef:
            name: route53-credentials-secret
            key: aws_access_key_id
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: aws_secret_access_key